services:
  - type: web
    runtime: docker
    name: ride-booking-api
    plan: free
    healthCheckPath: /swagger-ui.html
    envVars:
      - key: APP_JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ride-booking-db
          property: connectionString
      - key: SPRING_DATA_REDIS_URL
        fromService:
          name: ride-booking-cache
          type: keyvalue
          property: connectionString

  - type: keyvalue
    name: ride-booking-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: ride-booking-db
    plan: free
    databaseName: ridedb
    user: ride
